devices:
- name: Headpats
  ip: 192.168.1.69
  proximity_parameter: proximity_01
  online_parameter: Headpats_online
  max_speed: 37
  speed_scale: null
  max_speed_parameter: null
  use_velocity_control: null
  velocity_on_prox_drop: null
  outer_proximity: null
  inner_proximity: null
  velocity_scalar: 100
  velocity_softcap: 21
  velocity_smoothing_ms: 190
- name: Device 2
  ip: 192.168.1.70
  proximity_parameter: proximity_02
  online_parameter: Device_2_online
  max_speed: 100
  speed_scale: null
  max_speed_parameter: null
  use_velocity_control: null
  velocity_on_prox_drop: null
  outer_proximity: null
  inner_proximity: null
  velocity_scalar: null
  velocity_softcap: null
  velocity_smoothing_ms: null
setup:
  port_rx: '9001'
  default_min_speed: 5
  default_max_speed: 25
  default_start_tx: 20
  default_max_speed_parameter: max_speed
  timeout: 5
  default_use_velocity_control: true
  default_velocity_on_prox_drop: false
  default_outer_proximity: 0.0
  default_inner_proximity: 1.0
  default_velocity_scalar: 20
  default_velocity_softcap: 35
  default_velocity_smoothing_ms: 0
  online_status_broadcast_seconds: 5
