devices:
- name: Headpats2
  ip: 192.168.1.69
  proximity_parameter: proximity_01
  online_parameter: Headpats2_online
  max_speed: 19
  speed_scale: null
  max_speed_parameter: max_speed1
  use_velocity_control: false
  velocity_on_prox_drop: true
  outer_proximity: null
  inner_proximity: null
  velocity_scalar: 19
  velocity_softcap: 29
  velocity_smoothing_ms: 130
- name: Device 2
  ip: 192.168.1.132
  proximity_parameter: proximity_02
  online_parameter: Device_2_online
  max_speed: 57
  speed_scale: null
  max_speed_parameter: max_speed
  use_velocity_control: false
  velocity_on_prox_drop: null
  outer_proximity: null
  inner_proximity: 0.5
  velocity_scalar: 29
  velocity_softcap: 23
  velocity_smoothing_ms: 250
setup:
  port_rx: '9001'
  default_min_speed: 5
  default_max_speed: 25
  default_start_tx: 20
  default_max_speed_parameter: max_speed
  timeout: 5
  default_use_velocity_control: true
  default_velocity_on_prox_drop: false
  default_outer_proximity: 0.0
  default_inner_proximity: 1.0
  default_velocity_scalar: 20
  default_velocity_softcap: 35
  default_velocity_smoothing_ms: 0
  online_status_broadcast_seconds: 5
