devices:
- name: Headpats
  ip: 192.168.1.69
  proximity_parameter: proximity_01
  max_speed: 12
  speed_scale: null
  max_speed_parameter: null
  use_velocity_control: null
  velocity_on_prox_drop: true
  outer_proximity: null
  inner_proximity: null
  velocity_scalar: 28
  velocity_smoothing_ms: 200
- name: null
  ip: 192.168.1.70
  proximity_parameter: proximity_02
  max_speed: 86
  speed_scale: null
  max_speed_parameter: null
  use_velocity_control: null
  velocity_on_prox_drop: null
  outer_proximity: null
  inner_proximity: 0.8500000238418579
  velocity_scalar: null
  velocity_smoothing_ms: null
setup:
  port_rx: OSCQuery
  default_min_speed: 5
  default_max_speed: 25
  default_start_tx: 20
  default_max_speed_parameter: max_speed
  timeout: 5
  default_use_velocity_control: false
  default_velocity_on_prox_drop: false
  default_outer_proximity: 0.0
  default_inner_proximity: 1.0
  default_velocity_scalar: 20
  default_velocity_smoothing_ms: 80
