devices:
- name: Headpats
  ip: 192.168.1.69
  proximity_parameter: proximity_01
  max_speed: 100
  speed_scale: null
  max_speed_parameter: null
  use_velocity_control: null
  outer_proximity: null
  inner_proximity: null
  velocity_scalar: null
- name: null
  ip: 192.168.1.70
  proximity_parameter: proximity_02
  max_speed: 37
  speed_scale: null
  max_speed_parameter: null
  use_velocity_control: null
  outer_proximity: null
  inner_proximity: null
  velocity_scalar: null
setup:
  port_rx: '9001'
  default_min_speed: 5
  default_max_speed: 25
  default_start_tx: 20
  default_max_speed_parameter: max_speed
  timeout: 5
  default_use_velocity_control: false
  default_outer_proximity: 0.0
  default_inner_proximity: 0.7
  default_velocity_scalar: 20
